## Build
FROM golang:1.20 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
RUN go build -o /hi-tracking

## Deploy
FROM gcr.io/distroless/base-debian10
WORKDIR /
COPY --from=build /hi-tracking /hi-tracking
ENTRYPOINT ["/hi-tracking"]
