# fly.toml file generated for togo on 2023-04-11T11:26:56+07:00

app = "togo"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile-server"

[env]
  ENVIRONMENT = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
