name: Fly Deploy
on:
  push:
    branches:
      - 'master'
    paths:
      - 'internal/**'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'fly.toml'
      - 'Dockerfile-server'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
